# Generated by Django 5.2.1 on 2025-11-24 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
        ('rides', '0002_alter_ride_vehicle_type'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='driver',
            name='drivers_dri_license_9bdaab_idx',
        ),
        migrations.RemoveIndex(
            model_name='driverrating',
            name='drivers_rat_rider_i_b9e48a_idx',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_color',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_year',
        ),
        migrations.AddField(
            model_name='driver',
            name='current_vehicle',
            field=models.ForeignKey(blank=True, help_text='The vehicle currently being driven', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_driver', to='vehicles.vehicle'),
        ),
        migrations.AddIndex(
            model_name='driverrating',
            index=models.Index(fields=['rating'], name='drivers_rat_rating_0372d1_idx'),
        ),
    ]
