# Generated by Django 5.2.7 on 2025-12-12 15:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_remove_driver_drivers_dri_license_9bdaab_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.CreateModel(
            name='DriverBackgroundCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Background check expiry date (usually 1 year)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('provider', models.CharField(blank=True, help_text='Background check provider name', max_length=100, null=True)),
                ('provider_reference', models.CharField(blank=True, help_text="Provider's reference ID", max_length=200, null=True)),
                ('criminal_record_check', models.BooleanField(default=False, help_text='Criminal record background check passed')),
                ('driving_record_check', models.BooleanField(default=False, help_text='Driving record check passed')),
                ('identity_verification', models.BooleanField(default=False, help_text='Identity verification passed')),
                ('report_url', models.URLField(blank=True, help_text='URL to full background check report', null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about background check', null=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_checks', to='drivers.driver')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_background_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Background Check',
                'verbose_name_plural': 'Background Checks',
                'db_table': 'drivers_background_check',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', 'status'], name='drivers_bac_driver__723b95_idx'), models.Index(fields=['status', '-created_at'], name='drivers_bac_status_9ef77c_idx')],
            },
        ),
    ]
