# Generated by Django 5.2.7 on 2025-12-19 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_alter_driver_rating_driverbackgroundcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Current latitude (-90 to 90)', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Current longitude (-180 to 180)', max_digits=11)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, help_text='Direction driver is heading (0-360 degrees)', max_digits=5, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, help_text='Speed in km/h', max_digits=5, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters', max_digits=6, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.OneToOneField(help_text='Driver whose location this is', on_delete=django.db.models.deletion.CASCADE, related_name='location', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Driver Location',
                'verbose_name_plural': 'Driver Locations',
                'db_table': 'drivers_location',
                'indexes': [models.Index(fields=['driver', '-updated_at'], name='drivers_loc_driver__44e346_idx'), models.Index(fields=['latitude', 'longitude'], name='drivers_loc_latitud_0433ea_idx')],
            },
        ),
    ]
