# Generated by Django 5.2.7 on 2025-12-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_driverlocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverLocation',
        ),
    ]
