# Generated by Django 5.2.7 on 2025-12-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('wallet', 'Wallet'), ('card', 'Card')], default='cash', help_text='Payment method for this ride', max_length=20),
        ),
        migrations.AddField(
            model_name='ride',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
