# Generated by Django 5.2.7 on 2025-12-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_driverlocation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedlocation',
            name='label',
            field=models.CharField(blank=True, help_text="Custom label (e.g., 'Gym', 'Mom's House', 'Favorite Restaurant')", max_length=100, null=True),
        ),
    ]
