# Generated by Django 5.2.7 on 2025-11-10 21:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('approve', 'Approve'), ('reject', 'Reject'), ('suspend', 'Suspend'), ('activate', 'Activate'), ('payment', 'Payment'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal'), ('cancel', 'Cancel'), ('complete', 'Complete'), ('rate', 'Rate'), ('security', 'Security Event'), ('admin', 'Admin Action'), ('system', 'System Event')], help_text='Type of action performed', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Severity level of the action', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of object affected', null=True)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('request_path', models.CharField(blank=True, help_text='API endpoint or URL path', max_length=500)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the action')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the action occurred')),
                ('success', models.BooleanField(default=True, help_text='Whether the action was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of object affected', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for system events)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_log_user_id_835db7_idx'), models.Index(fields=['action_type', 'timestamp'], name='audit_log_action__ebbe27_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_log_content_10f046_idx'), models.Index(fields=['severity', 'timestamp'], name='audit_log_severit_917ad4_idx'), models.Index(fields=['ip_address', 'timestamp'], name='audit_log_ip_addr_f3d5f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('failed_login', 'Failed Login'), ('suspicious_activity', 'Suspicious Activity'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('unauthorized_access', 'Unauthorized Access'), ('data_breach_attempt', 'Data Breach Attempt'), ('sql_injection_attempt', 'SQL Injection Attempt'), ('xss_attempt', 'XSS Attempt'), ('csrf_violation', 'CSRF Violation'), ('account_locked', 'Account Locked'), ('password_reset_abuse', 'Password Reset Abuse')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='IP address of the request')),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False, help_text='Whether the security event has been resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'db_table': 'security_event',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='security_ev_event_t_0b896c_idx'), models.Index(fields=['severity', 'timestamp'], name='security_ev_severit_070cf6_idx'), models.Index(fields=['ip_address', 'timestamp'], name='security_ev_ip_addr_db6ebc_idx'), models.Index(fields=['resolved', 'timestamp'], name='security_ev_resolve_368cd0_idx')],
            },
        ),
    ]
